src/Entity/Reservation.php
<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use App\Repository\ReservationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
#[ApiResource]
#[ApiFilter(SearchFilter::class, properties: ['id_user' => 'exact'])]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Offre $id_offre = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    private ?Commercial $id_commercial = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $id_user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_reservation = null;

    #[ORM\Column]
    private ?int $num_voyageurs = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $remarque = null;

    #[ORM\Column(nullable: true)]
    private ?float $Mnt_commission = null;

    #[ORM\Column(nullable: true)]
    private ?float $avance_commission = null;

    #[ORM\OneToMany(mappedBy: 'id_reservation', targetEntity: Avance::class, orphanRemoval: true)]
    private Collection $avances;

    #[ORM\OneToMany(mappedBy: 'id_reservation', targetEntity: Voyageur::class, orphanRemoval: true)]
    private Collection $voyageurs;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_avance_commission = null;

    #[ORM\Column]
    private ?float $montant_total = null;

    public function __construct()
    {
        $this->avances = new ArrayCollection();
        $this->voyageurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): void
    {
        $this->id = $id;
    }

    public function getIdOffre(): ?Offre
    {
        return $this->id_offre;
    }

    public function setIdOffre(?Offre $id_offre): self
    {
        $this->id_offre = $id_offre;

        return $this;
    }

    public function getIdCommercial(): ?Commercial
    {
        return $this->id_commercial;
    }

    public function setIdCommercial(?Commercial $id_commercial): self
    {
        $this->id_commercial = $id_commercial;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getDateReservation(): ?\DateTimeInterface
    {
        return $this->date_reservation;
    }

    public function setDateReservation(\DateTimeInterface $date_reservation): self
    {
        $this->date_reservation = $date_reservation;

        return $this;
    }

    public function getNumVoyageurs(): ?int
    {
        return $this->num_voyageurs;
    }

    public function setNumVoyageurs(int $num_voyageurs): self
    {
        $this->num_voyageurs = $num_voyageurs;

        return $this;
    }

    public function getRemarque(): ?string
    {
        return $this->remarque;
    }

    public function setRemarque(?string $remarque): self
    {
        $this->remarque = $remarque;

        return $this;
    }

    public function getMntCommission(): ?float
    {
        return $this->Mnt_commission;
    }

    public function setMntCommission(?float $Mnt_commission): self
    {
        $this->Mnt_commission = $Mnt_commission;

        return $this;
    }

    public function getAvanceCommission(): ?float
    {
        return $this->avance_commission;
    }

    public function setAvanceCommission(?float $avance_commission): self
    {
        $this->avance_commission = $avance_commission;

        return $this;
    }


    /**
     * @return Collection<int, Avance>
     */
    public function getAvances(): Collection
    {
        return $this->avances;
    }

    public function addAvance(Avance $avance): self
    {
        if (!$this->avances->contains($avance)) {
            $this->avances->add($avance);
            $avance->setIdReservation($this);
        }

        return $this;
    }

    public function removeAvance(Avance $avance): self
    {
        if ($this->avances->removeElement($avance)) {
            // set the owning side to null (unless already changed)
            if ($avance->getIdReservation() === $this) {
                $avance->setIdReservation(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Voyageur>
     */
    public function getVoyageurs(): Collection
    {
        return $this->voyageurs;
    }

    public function addVoyageur(Voyageur $voyageur): self
    {
        if (!$this->voyageurs->contains($voyageur)) {
            $this->voyageurs->add($voyageur);
            $voyageur->setIdReservation($this);
        }

        return $this;
    }

    public function removeVoyageur(Voyageur $voyageur): self
    {
        if ($this->voyageurs->removeElement($voyageur)) {
            // set the owning side to null (unless already changed)
            if ($voyageur->getIdReservation() === $this) {
                $voyageur->setIdReservation(null);
            }
        }

        return $this;
    }

    public function getDateAvanceCommission(): ?\DateTimeInterface
    {
        return $this->date_avance_commission;
    }

    public function setDateAvanceCommission(?\DateTimeInterface $date_avance_commission): self
    {
        $this->date_avance_commission = $date_avance_commission;

        return $this;
    }

    public function getMontantTotal(): ?float
    {
        return $this->montant_total;
    }

    public function setMontantTotal(float $montant_total): self
    {
        $this->montant_total = $montant_total;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('num_voyageurs', NumberType::class)
            ->add('remarque', TextareaType::class, ['required' => false])
            ->add('mnt_commission', TextType::class, ['required' => false])
            ->add('avance_commission', TextType::class, ['required' => false])
            ->add('voyageurs',CollectionType::class, [
                'entry_type' => VoyageurType::class,
                'label' => false,
                'required' => false,
                'attr' => [
                    'class' => 'hidden',
                ],
                'entry_options' => ['label' => false],
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true,
                'error_bubbling' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
            'allow_extra_fields' => true,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Service\ReservationApiService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/dashboard/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_reservation_index', methods: ['GET'])]
    public function index(ReservationApiService $ReservationApiService, Security $security): Response
    {
        if ($this->isGranted("ROLE_ADMIN")) $data = $ReservationApiService->getReservations();
        else $data = $ReservationApiService->getReservations($this->getUser()->getId());
        return $this->render('reservation/index.html.twig', [
            'reservations' => $data,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        if ($reservation->getIdUser()->getId() != $this->getUser()->getId()  && !$this->isGranted("ROLE_ADMIN")) {
            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, ReservationApiService $ReservationApiService): Response
    {
        // dd($reservation);
        if ($reservation->getIdUser()->getId() != $this->getUser()->getId() && !$this->isGranted("ROLE_ADMIN")) {
            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ReservationApiService->UpdateReservation($reservation);

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, ReservationApiService $ReservationApiService): Response
    {
        if ($reservation->getIdUser()->getId() != $this->getUser()->getId() && !$this->isGranted("ROLE_ADMIN")) {
            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $ReservationApiService->DeleteReservation($reservation->getId());
        }

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cet élément?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="w-full text-left block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Supprimer</button>
</form>

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Reservation{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('editReservation') }}
{% endblock %}

{% block body %}
   <h1 class="text-center my-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-xl lg:text-xl dark:text-white">RESERVATION NUMERO <span class="text-blue-600 dark:text-blue-500">#{{ reservation.id }}</span></h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_reservation_index') }}" class="flex items-center justify-center my-4 text-center font-medium text-blue-600 dark:text-blue-500 hover:underline ml-auto">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5 mr-1"><path fill-rule="evenodd" d="M18 10a.75.75 0 01-.75.75H4.66l2.1 1.95a.75.75 0 11-1.02 1.1l-3.5-3.25a.75.75 0 010-1.1l3.5-3.25a.75.75 0 111.02 1.1l-2.1 1.95h12.59A.75.75 0 0118 10z" clip-rule="evenodd" /></svg>
        retour à la liste des Reservation
    </a>

{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservations{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('datables') }}
{% endblock %}
{% block body %}
    <div class="flex justify-between mx-10 my-6">
        <h1 class=" text-3xl text-center font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-2xl"><span class="text-transparent bg-clip-text bg-gradient-to-r to-blue-600 from-blue-500">Reservations</span> </h1>
        <a href="{{ path('app_myoffres') }}" class="text-white bg-gradient-to-br from-blue-600 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 transition duration-300">Reserver</a>
    </div>

    <table class="table w-max m-auto rounded-xl" id="DataTables-Table">
        <thead class="bg-gray-50 border-b border-gray-200">
            <tr class="text-xs text-left font-medium text-gray-500 uppercase tracking-wider"><tr>
                <th class="px-4 py-3">Id</th>
                <th class="px-4 py-3">Date de reservation</th>
                <th class="px-4 py-3">Nombre de voyageurs</th>
                <th class="px-4 py-3">Montant de commission</th>
                <th class="px-4 py-3">Avance de commission</th>
                <th class="px-4 py-3">Date d'avance</th>
                <th class="px-4 py-3">Remarque</th>
                <th class="px-4 py-3">Actions</th>
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
        {% for reservation in reservations %}
            <tr class="text-sm text-gray-500">
                <td class="px-4 py-3 text-center">{{ reservation.id }}</td>
                <td class="px-4 py-3 text-center">{{ reservation.dateReservation ? reservation.dateReservation|date('Y-m-d H:i:s') : '' }}</td>
                <td class="px-4 py-3 text-center">{{ reservation.numVoyageurs }}</td>
                <td class="px-4 py-3 text-center">
                    {% if reservation.MntCommission %}
                        {{ reservation.MntCommission }}
                    {% else %}
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 m-auto text-gray-600"><path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15" /></svg>
                    {% endif %}
                </td>
                <td class="px-4 py-3 text-center">
                    {% if reservation.avanceCommission %}
                        {{ reservation.avanceCommission }}
                    {% else %}
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 m-auto text-gray-600"><path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15" /></svg>
                    {% endif %}
                </td>
                <td class="px-4 py-3 text-center">
                    {% if reservation.dateAvanceCommission %}
                        {{ reservation.dateReservation|date('Y-m-d H:i:s')}}
                    {% else %}
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 m-auto text-gray-600"><path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15" /></svg>
                    {% endif %}
                </td>
                <td class="px-4 py-3 text-center">
                    {% if reservation.remarque %}
                        {{ reservation.remarque }}
                    {% else %}
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 m-auto text-gray-600"><path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15" /></svg>
                    {% endif %}
                </td>
                <td class="px-4 py-3">
                    <div class="flex items-center space-x-2">
                        <div class="inline-flex rounded-md shadow-sm" role="group">
                            <a href="{{ path('app_reservation_show', {'id': reservation.id}) }}" data-popover-target="popover-show" data-popover-placement="top" class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-l-lg hover:bg-gray-100 hover:text-yellow-300 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4"><path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" /><path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
                            </a>
                            <div data-popover id="popover-show" role="tooltip" class="absolute z-10 invisible inline-block w-64 text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 dark:text-gray-400 dark:border-gray-600 dark:bg-gray-800">
                                <div class="px-3 py-2 bg-gray-100 border-b border-gray-200 rounded-t-lg dark:border-gray-600 dark:bg-gray-700">
                                    <h3 class="font-semibold text-gray-900 dark:text-white">Voir</h3>
                                </div>
                                <div class="px-3 py-2">
                                    <p>en cliquant, vous pouvez voir plus de détails sur cette réservation</p>
                                </div>
                                <div data-popper-arrow></div>
                            </div>
                            <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}" data-popover-target="popover-edit" data-popover-placement="top" class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-l-transparent border-gray-200 hover:bg-gray-100 hover:text-blue-500 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4"><path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" /></svg>
                            </a>
                            <div data-popover id="popover-edit" role="tooltip" class="absolute z-10 invisible inline-block w-64 text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 dark:text-gray-400 dark:border-gray-600 dark:bg-gray-800">
                                <div class="px-3 py-2 bg-gray-100 border-b border-gray-200 rounded-t-lg dark:border-gray-600 dark:bg-gray-700">
                                    <h3 class="font-semibold text-gray-900 dark:text-white">Modifier</h3>
                                </div>
                                <div class="px-3 py-2">
                                    <p>en un clic, vous pouvez modifier cette réservation</p>
                                </div>
                                <div data-popper-arrow></div>
                            </div>
                            <a href="{{ path('app_avance_index', {'idR': reservation.id}) }}" data-popover-target="popover-avance" data-popover-placement="top" class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-l-transparent border-gray-200 hover:bg-gray-100 hover:text-green-500 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4"><path stroke-linecap="round" stroke-linejoin="round" d="M2.25 18.75a60.07 60.07 0 0115.797 2.101c.727.198 1.453-.342 1.453-1.096V18.75M3.75 4.5v.75A.75.75 0 013 6h-.75m0 0v-.375c0-.621.504-1.125 1.125-1.125H20.25M2.25 6v9m18-10.5v.75c0 .414.336.75.75.75h.75m-1.5-1.5h.375c.621 0 1.125.504 1.125 1.125v9.75c0 .621-.504 1.125-1.125 1.125h-.375m1.5-1.5H21a.75.75 0 00-.75.75v.75m0 0H3.75m0 0h-.375a1.125 1.125 0 01-1.125-1.125V15m1.5 1.5v-.75A.75.75 0 003 15h-.75M15 10.5a3 3 0 11-6 0 3 3 0 016 0zm3 0h.008v.008H18V10.5zm-12 0h.008v.008H6V10.5z" /></svg>
                            </a>
                            <div data-popover id="popover-avance" role="tooltip" class="absolute z-10 invisible inline-block w-64 text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 dark:text-gray-400 dark:border-gray-600 dark:bg-gray-800">
                                <div class="px-3 py-2 bg-gray-100 border-b border-gray-200 rounded-t-lg dark:border-gray-600 dark:bg-gray-700">
                                    <h3 class="font-semibold text-gray-900 dark:text-white">Avances</h3>
                                </div>
                                <div class="px-3 py-2">
                                    <p>en cliquant, vous pouvez voir les avances de cette réservation</p>
                                </div>
                                <div data-popper-arrow></div>
                            </div>
                            <a href="{{ path('app_voyageur_index', {'idR': reservation.id}) }}" data-popover-target="popover-voyageur" data-popover-placement="top" class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-l-transparent border-gray-200 hover:bg-gray-100 hover:text-red-500 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4"><path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" /></svg>
                            </a>
                            <div data-popover id="popover-voyageur" role="tooltip" class="absolute z-10 invisible inline-block w-64 text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 dark:text-gray-400 dark:border-gray-600 dark:bg-gray-800">
                                <div class="px-3 py-2 bg-gray-100 border-b border-gray-200 rounded-t-lg dark:border-gray-600 dark:bg-gray-700">
                                    <h3 class="font-semibold text-gray-900 dark:text-white">Voyageurs</h3>
                                </div>
                                <div class="px-3 py-2">
                                    <p>en cliquant, vous pouvez voir les Voyageurs de cette réservation</p>
                                </div>
                                <div data-popper-arrow></div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Aucun reservation trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Reservation{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('newReservation') }}
{% endblock %}

{% block body %}
    <h1 class="text-center mt-12 mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-xl lg:text-xl dark:text-white">CREER UNE RESERVATION POUR L'OFFRE <span class="text-blue-600 dark:text-blue-500">#{{ idOffre }}</span></h1>


    {{ include('reservation/_form.html.twig') }}
    <input type="hidden" id="CommercialData" value={{commercials}} />

    <a href="{{ path('app_reservation_index') }}" class="flex items-center justify-center mt-4 mb-12 text-center font-medium text-blue-600 dark:text-blue-500 hover:underline ml-auto">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5 mr-1"><path fill-rule="evenodd" d="M18 10a.75.75 0 01-.75.75H4.66l2.1 1.95a.75.75 0 11-1.02 1.1l-3.5-3.25a.75.75 0 010-1.1l3.5-3.25a.75.75 0 111.02 1.1l-2.1 1.95h12.59A.75.75 0 0118 10z" clip-rule="evenodd" /></svg>
        retour à la liste des offres
    </a>
{% endblock %}