src/Entity/Newsletters/Categories.php
<?php

namespace App\Entity\Newsletters;

use App\Repository\Newsletters\CategoriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoriesRepository::class)]
class Categories
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToMany(targetEntity: Users::class, mappedBy: 'categories')]
    private Collection $users;

    #[ORM\OneToMany(mappedBy: 'categories', targetEntity: Newsletters::class, orphanRemoval: true)]
    private Collection $newsletters;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->newsletters = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Users>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(Users $user): self
    {
        // if (!$this->users->contains($user)) {
        //     $this->users->add($user);
        // }
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addCategory($this);
        }

        return $this;
    }

    public function removeUser(Users $user): self
    {
        $this->users->removeElement($user);

        return $this;
    }

    /**
     * @return Collection<int, Newsletters>
     */
    public function getNewsletters(): Collection
    {
        return $this->newsletters;
    }

    public function addNewsletter(Newsletters $newsletter): self
    {
        if (!$this->newsletters->contains($newsletter)) {
            $this->newsletters->add($newsletter);
            $newsletter->setCategories($this);
        }

        return $this;
    }

    public function removeNewsletter(Newsletters $newsletter): self
    {
        if ($this->newsletters->removeElement($newsletter)) {
            // set the owning side to null (unless already changed)
            if ($newsletter->getCategories() === $this) {
                $newsletter->setCategories(null);
            }
        }

        return $this;
    }
}

src/Entity/Newsletters/Newsletters.php
<?php

namespace App\Entity\Newsletters;

use App\Repository\Newsletters\NewslettersRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NewslettersRepository::class)]
class Newsletters
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_sent = null;

    #[ORM\ManyToOne(inversedBy: 'newsletters')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $categories = null;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function isIsSent(): ?bool
    {
        return $this->is_sent;
    }

    public function setIsSent(bool $is_sent): self
    {
        $this->is_sent = $is_sent;

        return $this;
    }

    public function getCategories(): ?Categories
    {
        return $this->categories;
    }

    public function setCategories(?Categories $categories): self
    {
        $this->categories = $categories;

        return $this;
    }
}

src/Form/Newsletters/CategoriesType.php
<?php

namespace App\Form\Newsletters;

use App\Entity\Newsletters\Categories;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoriesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            // ->add('users')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Categories::class,
        ]);
    }
}

src/Form/NewslettersType.php
<?php

namespace App\Form;

use App\Entity\Newsletters\Categories;
use App\Entity\Newsletters\Newsletters;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NewslettersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('content', TextType::class)
            ->add('categories', EntityType::class, [
                'class' => Categories::class,
                'choice_label' => 'name'
            ])
            // ->add('enregistrer', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Newsletters::class,
        ]);
    }
}

src/Controller/Newsletters/CategoriesController.php
<?php

namespace App\Controller\Newsletters;

use App\Entity\Newsletters\Categories;
use App\Form\Newsletters\CategoriesType;
use App\Repository\Newsletters\CategoriesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\Newsletters\UsersRepository;
use App\Repository\Newsletters\NewslettersRepository;
use Doctrine\Persistence\ManagerRegistry;


#[Route('dashboard/newsletters/categories')]
class CategoriesController extends AbstractController
{
    private ManagerRegistry $doctrine;

    public function __construct(ManagerRegistry $doctrine)
    {
        $this->doctrine = $doctrine;
    }
    #[Route('/', name: 'app_newsletters_categories_index', methods: ['GET'])]
    public function index(CategoriesRepository $categoriesRepository, NewslettersRepository $newsletters,  UsersRepository $users): Response
    {
        return $this->render('newsletters/categories/index.html.twig', [
            'categories' => $categoriesRepository->findAll(),
            'newsletters' => $newsletters->findAll(),
            'users' => $users->findAll()
        ]);
    }

    #[Route('/new', name: 'app_newsletters_categories_new', methods: ['GET', 'POST'])]

    public function new(Request $request): Response
    {
        $categories = new Categories();
        $form = $this->createForm(CategoriesType::class, $categories);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->doctrine->getManager("default");
            $em->persist($categories);
            $em->flush();

            return $this->redirectToRoute('app_newsletters_categories_index');
        }

        return $this->render('newsletters/categories/new.html.twig', [
            'form' => $form->createView()
        ]);
    }


    #[Route('/{id}', name: 'app_newsletters_categories_show', methods: ['GET'])]
    public function show(Categories $category): Response
    {
        return $this->render('newsletters/categories/show.html.twig', [
            'category' => $category,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_newsletters_categories_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Categories $category, CategoriesRepository $categoriesRepository, NewslettersRepository $newsletters,  UsersRepository $users): Response
    {
        $form = $this->createForm(CategoriesType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categoriesRepository->save($category, true);

            return $this->redirectToRoute('app_newsletters_categories_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('newsletters/categories/edit.html.twig', [
            'category' => $category,
            'form' => $form,
            // 'categories' => $categoriesRepository->findAll(),
            'newsletters' => $newsletters->findAll(),
            'users' => $users->findAll()
        ]);
    }

    #[Route('/{id}', name: 'app_newsletters_categories_delete', methods: ['POST'])]
    public function delete(Request $request, Categories $categories, CategoriesRepository $categoriesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$categories->getId(), $request->request->get('_token'))) {
            $categoriesRepository->remove($categories, true);
        }

        return $this->redirectToRoute('app_newsletters_categories_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/NewslettersController.php
<?php

namespace App\Controller;

use App\Entity\Newsletters\Categories;
use App\Entity\Newsletters\Newsletters;
use App\Entity\Newsletters\Users;
use App\Form\NewslettersType;
use App\Form\NewslettersUsersType;
use App\Form\NewslettersCategoriesType;
use App\Message\SendNewsletterMessage;
use App\Repository\Newsletters\CategoriesRepository;
use App\Repository\Newsletters\NewslettersRepository;
use App\Repository\Newsletters\UsersRepository;
use App\Service\SendNewsletterService;
use Doctrine\Persistence\ManagerRegistry;
use Exception;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mailer\Transport;
use Twig\Environment;


#[Route('/dashboard/newsletters')]

class NewslettersController extends AbstractController
{

    protected $templating;
    private ManagerRegistry $doctrine;

    public function __construct(ManagerRegistry $doctrine, Environment $templating,)
    {
        $this->doctrine = $doctrine;
        $this->templating = $templating;
    }

   
    #[Route('/list', name: 'list')]

    public function list(NewslettersRepository $newsletters): Response
    {
        return $this->render('newsletters/list.html.twig', [
            'newsletters' => $newsletters->findAll()
        ]);
    }

    #[Route('/prepare', name: 'prepare')]

    public function prepare(Request $request): Response
    {
        $newsletter = new Newsletters();
        $form = $this->createForm(NewslettersType::class, $newsletter);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->doctrine->getManager("default");
            $em->persist($newsletter);
            $em->flush();

            return $this->redirectToRoute('list');
        }

        return $this->render('newsletters/prepare.html.twig', [
            'form' => $form->createView()
        ]);
    }
    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Newsletters $newsletter, NewslettersRepository $NewslettersRepository): Response
    {
        $form = $this->createForm(NewslettersType::class, $newsletter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $NewslettersRepository->save($newsletter, true);

            return $this->redirectToRoute('list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('newsletters/edit.html.twig', [
            'newsletter' => $newsletter,
            'form' => $form,
            // 'categories' => $categoriesRepository->findAll(),
            // 'newsletters' => $newsletters->findAll(),
            // 'users' => $users->findAll()
        ]);
    }


    #[Route('/send/{id}', name: 'send')]

    public function send(Newsletters $newsletter, MessageBusInterface $messageBus,  MailerInterface $mailer): Response
    {
        $users = $newsletter->getCategories()->getUsers();

        $user = new Users();
        $token = hash('sha256', uniqid());
        
        // Pour redirect vers le template :
            $html = $this->templating->render(
                'emails/newsletter.html.twig',
                [
                    'user' => $user,
                    'token' => $token,
                    'newsletter' => $newsletter
                ]
            );
        foreach($users as $user){
            if($user->getIsValid()){
                $email = (new TemplatedEmail())
                ->from('Newsletter@norsys.fr')
                ->to($user->getEmail())
                ->subject('Newsletters Norsys')
                ->html($html);
                $dsn = $this->getParameter("mailtrap.param");
                $transport = Transport::fromDsn($dsn);
                $mailer = new Mailer($transport);
    
                $mailer->send($email);

                $messageBus->dispatch(new SendNewsletterMessage($user->getId(), $newsletter->getId()));
            }
        }

        // $newsletter->setIsSent(true);

        // $em = $this->doctrine->getManager("default");
        // $em->persist($newsletter);
        // $em->flush();

        return $this->redirectToRoute('list');
    }

    /**
     * @Route("/unsubscribe/{id}/{newsletter}/{token}", name="unsubscribe")
     */
    #[Route('/unsubscribe/{id}/{newsletter}/{token}', name: 'unsubscribe')]

    public function unsubscribe(Users $user, Newsletters $newsletter, $token): Response
    {
        if ($user->getValidationToken() != $token) {
            throw $this->createNotFoundException('Page non trouvée');
        }

        $em = $this->doctrine->getManager("default");

        if (count($user->getCategories()) > 1) {
            $user->removeCategory($newsletter->getCategories());
            $em->persist($user);
        } else {
            $em->remove($user);
        }
        $em->flush();

        $this->addFlash('message', 'Newsletter supprimée');

        return $this->redirectToRoute('app_main_news');
    }
    
           

}

templates/newsletters/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 transition duration-300 block m-auto">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/newsletters/list.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Liste des Newsletters{% endblock %}

{% block body %}
    <h1>Liste des newsletters</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Titre</th>
                <th>Date</th>
                <th>Catégorie</th>
                <th>Inscrits</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for newsletter in newsletters %}
                <tr>
                    <td>{{newsletter.id}}</td>
                    <td>{{newsletter.name}}</td>
                    <td>{{newsletter.createdAt|date}}</td>
                    <td>{{newsletter.categories.name}}</td>
                    <td>{{newsletter.categories.users|length}}</td>
                    <td>
                        {% if newsletter.isSent == false %}
                            <a href="{{ path('send', {id: newsletter.id}) }}">Envoyer</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        
        </tbody>
    </table>
{% endblock %} #}


{% extends 'base.html.twig' %}

{% block title %}Liste des Newsletters{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('datables') }}
{% endblock %}
{% block body %}
    <div class="flex justify-between mx-10 my-4">
        <h1 class=" text-3xl text-center font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-2xl"><span class="text-transparent bg-clip-text bg-gradient-to-r to-blue-600 from-blue-500">Liste des Newsletters</span> </h1>
            <a href="{{ path('app_newsletters_categories_index') }}" class="text-white bg-gradient-to-br from-blue-600 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 transition duration-300">Voir les categories des Newsletter</a>
            <a href="{{ path('prepare') }}" class="text-white bg-gradient-to-br from-blue-600 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 transition duration-300">Ajouter Newsletter</a>
    </div>
    <table class="table w-11/12 m-auto rounded-xl" id="DataTables-Table">
        <thead class="bg-gray-50 border-b border-gray-200">
            <tr class="text-xs text-left font-medium text-gray-500 uppercase tracking-wider">
                <th class="px-4 py-3 text-center">Id</th>
                <th class="px-4 py-3 text-center">Titre</th>
                <th class="px-4 py-3 text-center">Date de creation</th>
                <th class="px-4 py-3 text-center">Catégorie</th>
                <th class="px-4 py-3 text-center">Inscrits</th>
                <th class="px-4 py-3 text-center">actions</th>
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
      
           {% for newsletter in newsletters %}
            <tr class="text-sm text-gray-500">
                <td class="px-4 py-3 text-center">{{newsletter.id}}</td>
                <td class="px-4 py-3 text-center">{{newsletter.name}}</td>
                <td class="px-4 py-3 text-center">{{newsletter.createdAt|date}}</td>
                <td class="px-4 py-3 text-center">{{newsletter.categories.name}}</td>
                <td class="px-4 py-3 text-center">{{newsletter.categories.users|length}}</td>
                <td class="px-4 py-3 text-center">
                    <div class="flex items-center justify-center space-x-2">
                        <div class="inline-flex rounded-md shadow-sm" role="group">
                            {# {% if newsletter.isSent == false %}
                             <a href="{{ path('send', {id: newsletter.id}) }}">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" />
                                </svg>
                             </a>
                            {% endif %} #}


                            <a href="{{ path('edit', {'id': newsletter.id}) }}" data-popover-target="popover-edit" data-popover-placement="top" class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-l-lg hover:bg-gray-100 hover:text-yellow-300 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white ml-5">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4"><path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" /></svg>
                            </a>
                            <div data-popover id="popover-edit" role="tooltip" class="absolute z-10 invisible inline-block w-64 text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 dark:text-gray-400 dark:border-gray-600 dark:bg-gray-800">
                                <div class="px-3 py-2 bg-gray-100 border-b border-gray-200 rounded-t-lg dark:border-gray-600 dark:bg-gray-700">
                                    <h3 class="font-semibold text-gray-900 dark:text-white">Modifier</h3>
                                </div>
                                <div class="px-3 py-2">
                                    <p>en un clic, vous pouvez modifier.</p>
                                </div>
                                <div data-popper-arrow></div>
                            </div>
                        
                            {# <a href="{{ path('list', {'id': newsletter.id}) }}" data-popover-target="popover-edit" data-popover-placement="top" class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border-t border-b border-r rounded-r-lg border-gray-200 hover:bg-gray-100 hover:text-green-500 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" />
                                </svg>                            
                            </a> #}
                             {% if newsletter.isSent == false %}
                             <a href="{{ path('send', {id: newsletter.id}) }}" data-popover-target="popover-envoi" data-popover-placement="top" class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border-t border-b border-r rounded-r-lg border-gray-200 hover:bg-gray-100 hover:text-green-500 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" />
                                </svg>
                             </a>
                            {% endif %}
                            <div data-popover id="popover-edit" role="tooltip" class="absolute z-10 invisible inline-block w-64 text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 dark:text-gray-400 dark:border-gray-600 dark:bg-gray-800">
                                <div class="px-3 py-2 bg-gray-100 border-b border-gray-200 rounded-t-lg dark:border-gray-600 dark:bg-gray-700">
                                    <h3 class="font-semibold text-gray-900 dark:text-white">Modifier</h3>
                                </div>
                                <div class="px-3 py-2">
                                    <p>en un clic, vous pouvez modifier les informations de la newslatter.</p>
                                </div>
                                <div data-popper-arrow></div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            {% if is_granted('ROLE_ADMIN') %}               
            <div id="medium-modal" tabindex="-1" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
                <div class="relative w-full max-w-lg max-h-full">
                    <!-- Modal content -->
                    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                        <!-- Modal header -->
                        <div class="flex items-center justify-between p-5  rounded-t dark:border-gray-600">
                            <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="medium-modal">
                                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                                <span class="sr-only">Close modal</span> 
                            </button>
                        </div>
                        <!-- Modal body -->
                    </div>
                </div>
            </div>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}