src/Entity/Offre.php
<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
#[ApiResource]
#[ApiFilter(SearchFilter::class, properties: ['id_user' => 'exact'])]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $titre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: false)]
    private ?\DateTimeInterface $date_depart = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: false)]
    private ?\DateTimeInterface $date_retour = null;

    #[ORM\Column(nullable: true)]
    private ?bool $bhebergement = null;

    #[ORM\Column(nullable: true)]
    private ?bool $bvisa = null;

    #[ORM\Column(nullable: true)]
    private ?bool $bdemi_pension = null;

    #[ORM\Column(nullable: true)]
    private ?bool $bpension_complete = null;

    #[ORM\Column(nullable: true)]
    private ?bool $bvisite_medine = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix_un = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix_double = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix_triple = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix_quad = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix_quint = null;

    #[ORM\Column(nullable: true)]
    private ?bool $bcoup_coeur = null;

    #[ORM\Column(nullable: true)]
    private ?bool $bpubier = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_publication = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin_publication = null;

    #[ORM\Column(nullable: true)]
    private ?bool $bpassport = null;

    #[ORM\Column(nullable: true)]
    private ?bool $bphotos = null;

    #[ORM\Column(nullable: true)]
    private ?bool $bpass_vacinial = null;

    #[ORM\OneToMany(mappedBy: 'id_offre', targetEntity: Hotel::class, orphanRemoval: true)]
    private Collection $hotels;

    #[ORM\OneToMany(mappedBy: 'id_offre', targetEntity: Message::class, orphanRemoval: true)]
    private Collection $messages;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $detail_voyage = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $detail_vols = null;

    #[ORM\ManyToOne(cascade: ["persist"], targetEntity:"App\Entity\User")]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $id_user = null;

    #[ORM\ManyToOne(targetEntity:"App\Entity\Destination")]
    #[ORM\JoinColumn(nullable: false)]
    private ?Destination $id_destination = null;

    #[ORM\OneToMany(mappedBy: 'id_offre', targetEntity: Reservation::class, orphanRemoval: true)]
    private Collection $reservations;

    #[ORM\Column(nullable: true)]
    private ?float $prix_demi_pension = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix_complete_pension = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $detail_demi_pension = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $detail_complete_pension = null;

    #[ORM\ManyToOne(inversedBy: 'offers')]
    private ?CollectionOffre $categorieOffre = null;

    public function __construct()
    {
        $this->hotels = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): void
    {
        $this->id = $id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

    public function setDateRetour(\DateTimeInterface $date_retour): self
    {
        $this->date_retour = $date_retour;

        return $this;
    }

    public function isBhebergement(): ?bool
    {
        return $this->bhebergement;
    }

    public function setBhebergement(?bool $bhebergement): self
    {
        $this->bhebergement = $bhebergement;

        return $this;
    }

    public function isBvisa(): ?bool
    {
        return $this->bvisa;
    }

    public function setBvisa(?bool $bvisa): self
    {
        $this->bvisa = $bvisa;

        return $this;
    }

    public function isBdemiPension(): ?bool
    {
        return $this->bdemi_pension;
    }

    public function setBdemiPension(?bool $bdemi_pension): self
    {
        $this->bdemi_pension = $bdemi_pension;

        return $this;
    }

    public function isBpensionComplete(): ?bool
    {
        return $this->bpension_complete;
    }

    public function setBpensionComplete(?bool $bpension_complete): self
    {
        $this->bpension_complete = $bpension_complete;

        return $this;
    }

    public function isBvisiteMedine(): ?bool
    {
        return $this->bvisite_medine;
    }

    public function setBvisiteMedine(?bool $bvisite_medine): self
    {
        $this->bvisite_medine = $bvisite_medine;

        return $this;
    }

    public function isBcoupCoeur(): ?bool
    {
        return $this->bcoup_coeur;
    }

    public function setBcoupCoeur(?bool $bcoup_coeur): self
    {
        $this->bcoup_coeur = $bcoup_coeur;

        return $this;
    }

    public function isBpubier(): ?bool
    {
        return $this->bpubier;
    }

    public function setBpubier(?bool $bpubier): self
    {
        $this->bpubier = $bpubier;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->date_publication;
    }

    public function setDatePublication(?\DateTimeInterface $date_publication): self
    {
        $this->date_publication = $date_publication;

        return $this;
    }

    public function getDateFinPublication(): ?\DateTimeInterface
    {
        return $this->date_fin_publication;
    }

    public function setDateFinPublication(?\DateTimeInterface $date_fin_publication): self
    {
        $this->date_fin_publication = $date_fin_publication;

        return $this;
    }

    public function isBpassport(): ?bool
    {
        return $this->bpassport;
    }

    public function setBpassport(?bool $bpassport): self
    {
        $this->bpassport = $bpassport;

        return $this;
    }

    public function isBphotos(): ?bool
    {
        return $this->bphotos;
    }

    public function setBphotos(?bool $bphotos): self
    {
        $this->bphotos = $bphotos;

        return $this;
    }

    public function isBpassVacinial(): ?bool
    {
        return $this->bpass_vacinial;
    }

    public function setBpassVacinial(?bool $bpass_vacinial): self
    {
        $this->bpass_vacinial = $bpass_vacinial;

        return $this;
    }

    /**
     * @return Collection<int, Hotel>
     */
    public function getHotels(): Collection
    {
        return $this->hotels;
    }

    public function addHotel(Hotel $hotel): self
    {
        if (!$this->hotels->contains($hotel)) {
            $this->hotels->add($hotel);
            $hotel->setIdOffre($this);
        }

        return $this;
    }

    public function removeHotel(Hotel $hotel): self
    {
        if ($this->hotels->removeElement($hotel)) {
            // set the owning side to null (unless already changed)
            if ($hotel->getIdOffre() === $this) {
                $hotel->setIdOffre(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setIdOffre($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getIdOffre() === $this) {
                $message->setIdOffre(null);
            }
        }

        return $this;
    }

    public function getDetailVoyage(): ?string
    {
        return $this->detail_voyage;
    }

    public function setDetailVoyage(?string $detail_voyage): self
    {
        $this->detail_voyage = $detail_voyage;

        return $this;
    }

    public function getDetailVols(): ?string
    {
        return $this->detail_vols;
    }

    public function setDetailVols(?string $detail_vols): self
    {
        $this->detail_vols = $detail_vols;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getIdDestination(): ?Destination
    {

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tableau de bord{% endblock %}

{% block body %}
  <div class="flex flex-1 flex-col md:flex-row lg:flex-row mx-10 mt-20">
<!-- 1-->
  
            <div class="shadow-lg bg-red-400 hover:bg-red-500 hover:ease-in duration-300 border-red-vibrant-dark mb5 p-2 w-60 mx-2">
                <div class="p-4 flex flex-col">
                    <a href="/dashboard/myOffres" class="no-underline text-white text-2xl">
                       {{offres}}
                    </a>
                    <a href="/dashboard/myOffres" class="no-underline text-white text-lg">
                      Offres
                    </a>
                </div>
            </div>
<!-- 2-->
{% if is_granted('ROLE_ADMIN') %}
 <div class="shadow-lg bg-orange-400 hover:bg-orange-500 hover:ease-in duration-300 border-red-vibrant-dark mb5 p-2 w-60 mx-2">
                <div class="p-4 flex flex-col">
                    <a href="/dashboard/agent" class="no-underline text-white text-2xl">
                      {{agent}}
                    </a>
                    <a href="/dashboard/agent" class="no-underline text-white text-lg">
                    Agent
                    </a>
                </div>
            </div>
{% endif %}          
<!-- 3-->
 <div class="shadow-lg bg-green-400 hover:bg-green-500 hover:ease-in duration-300 border-red-vibrant-dark mb5 p-2 w-60 mx-2">
                <div class="p-4 flex flex-col">
                    <a href="/dashboard/message" class="no-underline text-white text-2xl">
                      {{messages}}
                    </a>
                    <a href="/dashboard/message" class="no-underline text-white text-lg">
                     Messages
                    </a>
                </div>
   </div>
   <!-- 4-->
 <div class="shadow-lg bg-cyan-400 hover:bg-cyan-500 hover:ease-in duration-300 border-red-vibrant-dark mb5 p-2 w-60 mx-2">
                <div class="p-4 flex flex-col">
                    <a href="/dashboard/commercial" class="no-underline text-white text-2xl">
                      {{commercial}}
                    </a>
                    <a href="/dashboard/commercial" class="no-underline text-white text-lg">
                      Commercial
                    </a>  
                </div>
   </div>
   <!-- 5-->
 <div class="shadow-lg bg-purple-400 hover:bg-purple-500 hover:ease-in duration-300 border-red-vibrant-dark mb5 p-2 w-60 mx-2">
                <div class="p-4 flex flex-col">
                    <a href="/dashboard/reservation" class="no-underline text-white text-2xl">
                      {{reservation}}
                    </a>
                    <a href="/dashboard/reservation" class="no-underline text-white text-lg">
                     Reservation
                    </a>
                </div>
   </div>
</div>



{% endblock %}

templates/dashboard/myoffres.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes Offres{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('offre') }}
{% endblock %}

{% block body %}
    <div class="flex justify-between mx-10 my-6">
        <h1 class=" text-3xl text-center font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-2xl"><span class="text-transparent bg-clip-text bg-gradient-to-r to-green-600 from-blue-500">Découvrez</span> votre offres.</h1>
        <a href="{{ path('app_offre_new') }}" class="text-white flex items-center bg-gradient-to-br from-green-400 to-blue-600 hover:scale-105 focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 transition-all duration-300">
            Ajouter une Offre
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 ml-2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 8.25H7.5a2.25 2.25 0 00-2.25 2.25v9a2.25 2.25 0 002.25 2.25h9a2.25 2.25 0 002.25-2.25v-9a2.25 2.25 0 00-2.25-2.25H15M9 12l3 3m0 0l3-3m-3 3V2.25" />
            </svg>
        </a>

    </div>
    <div class="grid grid-cols-2 gap-8 m-8">
    {% for offre in offres %}
        {# {{ dump(offre) }} #}
        <div class="flex justify-between items-center bg-white rounded-lg shadow-lg p-6 hover:scale-105 transition duration-500">
        <a href="{{ path('app_offre_show', {'id': offre.id}) }}" class="mr-8 hover:cursor-pointer">
            <div class="text-lg font-bold mb-2">{{ offre.titre }}</div>
            <div class="flex text-gray-600 mb-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6.115 5.19l.319 1.913A6 6 0 008.11 10.36L9.75 12l-.387.775c-.217.433-.132.956.21 1.298l1.348 1.348c.21.21.329.497.329.795v1.089c0 .426.24.815.622 1.006l.153.076c.433.217.956.132 1.298-.21l.723-.723a8.7 8.7 0 002.288-4.042 1.087 1.087 0 00-.358-1.099l-1.33-1.108c-.251-.21-.582-.299-.905-.245l-1.17.195a1.125 1.125 0 01-.98-.314l-.295-.295a1.125 1.125 0 010-1.591l.13-.132a1.125 1.125 0 011.3-.21l.603.302a.809.809 0 001.086-1.086L14.25 7.5l1.256-.837a4.5 4.5 0 001.528-1.732l.146-.292M6.115 5.19A9 9 0 1017.18 4.64M6.115 5.19A8.965 8.965 0 0112 3c1.929 0 3.716.607 5.18 1.64" />
                </svg>
                : {{ offre.idDestination }} 
            </div>
            <div class="inline-flex items-center text-gray-600 mb-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                : {{ offre.dateDepart ? offre.dateDepart|date('Y-m-d H:i') : '' }} &#160;
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12.75 15l3-3m0 0l-3-3m3 3h-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>&#160;{{ offre.dateRetour ? offre.dateRetour|date('Y-m-d H:i') : '' }}
            </div>
            {% if offre.prix_un is defined  %}
                <div class="text-lg font-bold text-green-800">{{ offre.prix_un }} MAD</div>
            {% else %}
                {% if offre.prix_double is defined %}
                    <div class="text-lg font-bold text-green-800">{{ offre.prix_double }} MAD</div>
                {% else %}
                    {% if offre.prix_double is defined %}
                        <div class="text-lg font-bold text-green-800">{{ offre.prix_double }} MAD</div>
                    {% else %}
                        {% if offre.prix_quad is defined %}
                            <div class="text-lg font-bold text-green-800">{{ offre.prix_quad }} MAD</div>
                        {% else %}
                            {% if offre.prix_quint is defined %}
                                <div class="text-lg font-bold text-green-800">{{ offre.prix_quint }} MAD</div>
                            {% endif %}
                        {% endif %}
                    {% endif %} 
                {% endif %}
            {% endif %}
        </a>
        {% if offre.image is defined %}
            <img data-modal-target="popup-modal" id='clickableImage' data-modal-toggle="popup-modal" src="{{ offre.image }}" alt="" class="w-32 h-32 object-cover rounded-lg hover:cursor-pointer">
           
        {% else %}
            <div class="w-32 h-32 bg-gray-300 rounded-lg"></div>
        {% endif %}
        </div>

         <div id="popup-modal"  tabindex="-1" class="fixed top-0 left-0 right-0 z-50 hidden p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
                <div class="relative w-full max-w-md max-h-full">
                    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                        <button type="button" class="absolute top-2.5 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-hide="popup-modal">
                            <svg aria-hidden="true" id="ClosePopUp" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                            <span class="sr-only">Close modal</span>
                        </button>
                        <div class="p-2 text-center rounded-lg" id="displayImage"></div>
                    </div>
                </div>
            </div>
        
    {% else %}
        <div class="text-gray-600">Aucun offre trouvé</div>
    {% endfor %}
    </div>


{% endblock %}